// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss']
})

export class AppComponent {
	todos: Array<any> = [];
	input: String = '';

	ngOnInit() {
		const storedData = localStorage.getItem('todos');
		this.todos = JSON.parse(storedData as string) || []
	}

	addItem () {
		const newItem = {
			description: this.input,
			completed: false
		};
		this.todos.push(newItem)
		localStorage.setItem('todos', JSON.stringify(this.todos));
		this.input = ''
	}

	deleteItem(index: number) {
		this.todos.splice(index, 1);
		localStorage.setItem('todos', JSON.stringify(this.todos));
	}

	toggleItemStatus(index: number) {
		this.todos[index][1] = !this.todos[index][1];
		localStorage.setItem('todos', JSON.stringify(this.todos));
	}
}

<div class="app">
	<div class="app--main">
		<img src="/assets/logo.svg" class="app--logo" alt="Logo" />
		<form class="app--main--add-item" (ngSubmit)="addItem()">
			<label>Add a task</label>
			<div>
				<input
					name="input"
					[(ngModel)]="input"
					placeholder="So, what's next?"
				>
				<button
					[disabled]="!(input.length>0)"
				>
				Add
				</button>
			</div>
		</form>
		<ul class="app--main--items">
			<li 
				*ngFor="let item of todos; let i = index"
				[attr.data-index]="i" 
				[ngClass]="{ 'completed' : item[1] == true }"
			>
				<button
					(click)="toggleItemStatus(i)"
				></button>
				<div class="app--main--items-item-text">
					{{ item.description }}
				</div>
				<button
					class="delete"
					(click)="deleteItem(i)"
				>
					&times;
				</button>
			</li>
		</ul>
	</div>
</div>

// react/src/App.js
import { useEffect, useState, useRef } from 'react';
import logo from './logo.svg';
import './App.scss';

function App() {

	const [todos, updateTodos] = useState([]);
	const itemDescription = useRef();

	useEffect(() => {
		const storedItems = localStorage.getItem('todos');
		updateTodos(storedItems ? JSON.parse(storedItems) : [])
	}, []);

	function isButtonDisabled() {
		if (itemDescription.current.value = '') {
			return false
		} else {
			return true
		}
	}

	function addItem(event) {
		event.preventDefault();
		const newItem = {
			description: itemDescription.current.value,
			completed: false
		};
		const updatedList = [...todos, newItem];
		updateTodos(updatedList);
		localStorage.setItem('todos', JSON.stringify(updatedList));
		itemDescription.current.value = ''
	}

	function deleteItem(index) {
		todos.splice(index, 1);
		const updatedList = [...todos]
		updateTodos(updatedList);
		localStorage.setItem('todos', JSON.stringify(updatedList));
	}

	function toggleItemStatus(index) {
		todos[index][1] = !todos[index][1]
		const updatedList = [...todos]
		updateTodos(updatedList);
		localStorage.setItem('todos', JSON.stringify(updatedList));
	}

	return (
		<div className="app">
			<div className="app--main">
				<img src={logo} className="app--logo" alt="Logo" />
				<form className="app--main--add-item" onSubmit={addItem}>
					<label>Add a task</label>
					<div>
						<input ref={itemDescription} placeholder="So, what's next?" />
						<button 
							disabled={itemDescription === ""}
						>
							Add
						</button>
					</div>
				</form>
				<ul className="app--main--items">
					{todos.map((item, index) => (
					<li key={index} className={ item[1] ? "completed" : ''}>
						<button
							onClick={() => toggleItemStatus(index)}
							>
						</button>
						<div className="app--main--items-item-text">
							{item.description}
						</div> 
						<button 
							className="delete"
							onClick={() => deleteItem(index)}
						>
							&times;
						</button>
					</li>
					))}
				</ul>
			</div>
		</div>
	);
}

export default App;
